#!/usr/bin/env python3
"""Translate with Sunbird's NLLB-1.3B (SALT) converted to CTranslate2 int8.

Languages: eng ach lgg lug nyn teo (no Swahili).
Usage: nllb_translate.py <model_dir> <src> <dst> "text" ["text" ...]
"""
import os
import sys
import time

import ctranslate2
import transformers

# Token ids from the model card (the SALT model added tokens to NLLB's vocab).
LANGUAGE_TOKENS = {
    "eng": 256047, "ach": 256111, "lgg": 256008,
    "lug": 256110, "nyn": 256002, "teo": 256006,
}


class Translator:
    def __init__(self, model_dir, threads=4, compute_type="int8"):
        self.tok = transformers.NllbTokenizer.from_pretrained(model_dir)
        self.tr = ctranslate2.Translator(model_dir, device="cpu", compute_type=compute_type,
                                         intra_threads=threads)
        self.last_tokens = 0  # tokens generated by the last translate() call

    def translate(self, text, src, dst, beam_size=None, max_len=100):
        beam_size = beam_size or int(os.environ.get("FAST_BEAM", "5"))  # 5 = the setting used in all earlier benchmarks
        ids = self.tok(text)["input_ids"]
        ids[0] = LANGUAGE_TOKENS[src]            # replace the source-language token
        tokens = self.tok.convert_ids_to_tokens(ids)
        target_prefix = [self.tok.convert_ids_to_tokens(LANGUAGE_TOKENS[dst])]
        res = self.tr.translate_batch([tokens], target_prefix=[target_prefix],
                                      beam_size=beam_size, max_decoding_length=max_len)
        out = res[0].hypotheses[0][1:]           # drop the target-language token
        self.last_tokens = len(out)
        return self.tok.decode(self.tok.convert_tokens_to_ids(out), skip_special_tokens=True)


if __name__ == "__main__":
    model_dir, src, dst, *texts = sys.argv[1:]
    t0 = time.time()
    tr = Translator(model_dir)
    print(f"load {time.time() - t0:.1f}s")
    for text in texts:
        t0 = time.time()
        print(f"{text!r} -> {tr.translate(text, src, dst)!r}  ({time.time() - t0:.2f}s)")
